### ISSUE TITLE
Conflict between bluetooth_proxy and esp32_ble_presense

### ISSUE THREAD

**Issue by tet024** [formatBCE/ESP32_BLE_presense#12]
Description:

I encountered an issue where using the bluetooth_proxy and esp32_ble_tracker plugins causes the esp32_ble_presense plugin to stop working. The esp32_ble_presense plugin remains in a scanning state and does not function as expected. When I remove the bluetooth_proxy plugin, the esp32_ble_presense plugin starts working again. This creates a problem as my Bluetooth Xiaomi temperature/humidity sensors rely on bluetooth_proxy to function properly.

Steps to Reproduce:

Configure bluetooth_proxy, esp32_ble_tracker, and esp32_ble_presense in the same environment.
Observe that the esp32_ble_presense plugin remains in a scanning state and does not work.
Remove the bluetooth_proxy plugin.
Observe that the esp32_ble_presense plugin starts working.

Expected Behavior:
The esp32_ble_presense plugin should work alongside bluetooth_proxy and esp32_ble_tracker without any issues, allowing all BLE requirements to be catered to simultaneously.

Actual Behavior:

The esp32_ble_presense plugin stops functioning and remains in  "BLE scan heartbeat" state when bluetooth_proxy is enabled.

When removed then: 
[format_ble:102][nimble_host]: Sending for '0E395EDA-C87A-437D-8782-E2FD325441B3': -97dBm -  Then it works

Environment:

ESP32 Device
Bluetooth Xiaomi Temperature/Humidity Sensors

Additional Context:
Is there a solution that can cater to all BLE requirements without causing conflicts between these plugins? Any guidance or workaround to resolve this issue would be greatly appreciated.

**Comment by formatBCE** [comment]
How do you expect it to work together? 
This component makes custom usage of Bluetooth stack to deliver beacons info as fast as possible for quick tracking. It uses 3rd party Bluetooth library for it, and takes 50% of antenna time (because antenna is shared with WiFi, and taking more will kill connection to the network). 
And you want it to co-exist with inbuilt Bluetooth functionality, which I wanted to get rid of?

There's ble_tracker in ESPHome, you can try using that instead. It won't conflict with proxy.

**Comment by tet024** [comment]
Thanks for the Clarification.
